version: 2

models:

    - name: sales
      tests:
        - unique:
            column_name: "(orders_id || '-' || products_id)"
            
      columns:
          - name: orders_id
            description: identifier of orders
            tests : 
            - not_null 

          - name: products_id
            description: idnetifier of products
            tests : 
            - not_null 

          - name: qty

          - name: turnover
            description: the total revenue resulting from sale of products
            tests : 
            - not_null 

          - name: purchase_cost
            description: the total cost associated with making the product
            tests : 
            - not_null 

          - name: margin
            description: the difference between the revenue and purcahse cost